name: Build and test on Windows, Linux and macOS

on:
  push:
    branches: [ "master", "dev", "runedev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  onWindows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgArguments: 'threepp'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
          vcpkgJsonGlob: 'vcpkg.json'
          appendedCacheKey: vcpkginstall

      - name: Configure CMake and build project
        run: |
          cmake . -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" -DTETRIS_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Release"
          cmake --build build

  #      - name: Test
  #        run: |
  #          cd build/tests
  #          ctest -C Release --output-on-failure

  onLinux:
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        compiler_version: [ 11 ]

    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libxinerama-dev \
          libxcursor-dev \
          xorg-dev \
          libglu1-mesa-dev \
          pkg-config

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
          vcpkgJsonGlob: 'vcpkg.json'
          appendedCacheKey: vcpkginstall

      - name: Configure CMake and build project
        run: |
          cmake . -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DTETRIS_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Release"
          cmake --build build

  #      - name: Test
  #        run: |
  #          cd build/tests
  #          ctest --output-on-failure

  onMacOS:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
          vcpkgJsonGlob: 'vcpkg.json'
          appendedCacheKey: vcpkginstall

      - name: Install prerequisites
        run: |
          brew install pkg-config

      - name: Configure CMake and build project
        run: |
          cmake . -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DTETRIS_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Release"
          cmake --build build
